document.addEventListener("DOMContentLoaded", () => {
  const container = document.getElementById("bookContainer");

  const renderPage = (search) => {
    const loggedInUser = JSON.parse(localStorage.getItem("loggedInUser"));

    // Clear previous content
    container.innerHTML = "";

    if (!loggedInUser) {
      const notLoggedInMsg = document.getElementById("notLoggedInMsg");
      const message = document.createElement("div");
      message.innerHTML = `<p>Please log in to view the price and Add to Cart.</p>`;
      notLoggedInMsg.appendChild(message);
    }

    // Filter books
    const items = search
      ? books.filter((book) =>
          book.title.toLowerCase().includes(search.toLowerCase()),
        )
      : books;

    if (items.length > 0) {
      // Render each book
      items.forEach((book, index) => {
        const card = document.createElement("div");
        card.classList.add("card");

        const cart = JSON.parse(localStorage.getItem("cart")) || [];

        card.innerHTML = `
          <img src="${book.imageLink}" alt="${book.title}">
          <h2>${book.title}</h2>
          <p><strong>Author:</strong> ${book.author}</p>
          <p><strong>Pages:</strong> ${book.pages}</p>
          <p><strong>Language:</strong> ${book.language}</p>
          <div class="footer">
            <div class="price" id="price-${index}">$${book.price}</div>
            <button class="addToCart btn primaryBtn" id="addToCart-${index}">
            Add To Cart <i class="fa-solid fa-cart-plus"></i></button>
            <p class="cartAdded" id="added-${index}" style="display: none;">
            Added to Cart!</p>
          </div>
      `;

        // Append the card and hide it initially
        $(container).append($(card).hide());

        // Add fade-in effect with a delay
        $(card)
          .delay(index * 300)
          .fadeIn(1000);

        // Add click event listener to the "Add To Cart" button
        const addToCartButton = card.querySelector(".addToCart");
        addToCartButton.addEventListener("click", () => {
          addToCart(book, index);
          $(`#addToCart-${index}`).hide();
          $(`#added-${index}`).show();
        });

        if (!loggedInUser) {
          console.log(loggedInUser);
          $(`#price-${index}`).hide();
          $(`#addToCart-${index}`).hide();
        } else {
          const bookExists = cart.some((item) => item.title === book.title);
          if (bookExists) {
            $(`#addToCart-${index}`).hide();
            $(`#added-${index}`).show();
          } else {
            $(`#addToCart-${index}`).show();
            $(`#added-${index}`).hide();
          }
        }
      });
    } else {
      const mainContainer = document.getElementById("container");

      const noBooksDiv = document.createElement("div");
      noBooksDiv.classList.add("noBooks");

      noBooksDiv.innerHTML = `
        <img src="images/empty-box.png" alt="No Items" width="250" height="250"/>
        <p>Sorry! No Books Found.</p>
      `;

      mainContainer.appendChild(noBooksDiv);
    }
  };

  renderPage();

  // Search button handler
  $("#search").click(function (event) {
    event.preventDefault();
    const searchText = $("#searchText").val();
    renderPage(searchText);
  });

  $("#searchText").on("keydown", function (event) {
    if (event.key === "Enter") {
      event.preventDefault();
      const searchText = $(this).val();
      renderPage(searchText);
    }
  });
});

// Function to add the book in the cart
const addToCart = (book, index) => {
  const cart = JSON.parse(localStorage.getItem("cart")) || [];

  cart.push({ ...book, quantity: 1 });

  localStorage.setItem("cart", JSON.stringify(cart));

  alert(`${book.title} has been added to the cart!`);
  $(`#addToCart-${index}`).hide();
  $(`#added-${index}`).show();
};

// List of books to display in the page
const books = [
  {
    author: "Chinua Achebe",
    country: "Nigeria",
    imageLink: "images/books/things-fall-apart.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Things_Fall_Apart\n",
    pages: 209,
    title: "Things Fall Apart",
    year: 1958,
    price: 10,
  },
  {
    author: "Hans Christian Andersen",
    country: "Denmark",
    imageLink: "images/books/fairy-tales.jpg",
    language: "Danish",
    link: "https://en.wikipedia.org/wiki/Fairy_Tales_Told_for_Children._First_Collection.\n",
    pages: 784,
    title: "Fairy tales",
    year: 1836,
    price: 99,
  },
  {
    author: "Dante Alighieri",
    country: "Italy",
    imageLink: "images/books/the-divine-comedy.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Divine_Comedy\n",
    pages: 928,
    title: "The Divine Comedy",
    year: 1315,
    price: 129.99,
  },
  {
    author: "Unknown",
    country: "Sumer and Akkadian Empire",
    imageLink: "images/books/the-epic-of-gilgamesh.jpg",
    language: "Akkadian",
    link: "https://en.wikipedia.org/wiki/Epic_of_Gilgamesh\n",
    pages: 160,
    title: "The Epic Of Gilgamesh",
    year: -1700,
    price: 51,
  },
  {
    author: "Unknown",
    country: "Achaemenid Empire",
    imageLink: "images/books/the-book-of-job.jpg",
    language: "Hebrew",
    link: "https://en.wikipedia.org/wiki/Book_of_Job\n",
    pages: 176,
    title: "The Book Of Job",
    year: -600,
    price: 70,
  },
  {
    author: "Unknown",
    country: "India/Iran/Iraq/Egypt/Tajikistan",
    imageLink: "images/books/one-thousand-and-one-nights.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/One_Thousand_and_One_Nights\n",
    pages: 288,
    title: "One Thousand and One Nights",
    year: 1200,
    price: 65,
  },
  {
    author: "Unknown",
    country: "Iceland",
    imageLink: "images/books/njals-saga.jpg",
    language: "Old Norse",
    link: "https://en.wikipedia.org/wiki/Nj%C3%A1ls_saga\n",
    pages: 384,
    title: "Nj\u00e1l's Saga",
    year: 1350,
    price: 19.99,
  },
  {
    author: "Jane Austen",
    country: "United Kingdom",
    imageLink: "images/books/pride-and-prejudice.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Pride_and_Prejudice\n",
    pages: 226,
    title: "Pride and Prejudice",
    year: 1813,
    price: 120,
  },
  {
    author: "Honor\u00e9 de Balzac",
    country: "France",
    imageLink: "images/books/le-pere-goriot.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Le_P%C3%A8re_Goriot\n",
    pages: 443,
    title: "Le P\u00e8re Goriot",
    year: 1835,
    price: 91,
  },
  {
    author: "Samuel Beckett",
    country: "Republic of Ireland",
    imageLink: "images/books/molloy-malone-dies-the-unnamable.jpg",
    language: "French, English",
    link: "https://en.wikipedia.org/wiki/Molloy_(novel)\n",
    pages: 256,
    title: "Molloy, Malone Dies, The Unnamable, the trilogy",
    year: 1952,
    price: 71,
  },
  {
    author: "Giovanni Boccaccio",
    country: "Italy",
    imageLink: "images/books/the-decameron.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/The_Decameron\n",
    pages: 1024,
    title: "The Decameron",
    year: 1351,
    price: 49,
  },
  {
    author: "Jorge Luis Borges",
    country: "Argentina",
    imageLink: "images/books/ficciones.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Ficciones\n",
    pages: 224,
    title: "Ficciones",
    year: 1965,
    price: 30,
  },
  {
    author: "Emily Bront\u00eb",
    country: "United Kingdom",
    imageLink: "images/books/wuthering-heights.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Wuthering_Heights\n",
    pages: 342,
    title: "Wuthering Heights",
    year: 1847,
    price: 54,
  },
  {
    author: "Albert Camus",
    country: "Algeria, French Empire",
    imageLink: "images/books/l-etranger.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/The_Stranger_(novel)\n",
    pages: 185,
    title: "The Stranger",
    year: 1942,
    price: 67,
  },
  {
    author: "Paul Celan",
    country: "Romania, France",
    imageLink: "images/books/poems-paul-celan.jpg",
    language: "German",
    link: "\n",
    pages: 320,
    title: "Poems",
    year: 1952,
    price: 94,
  },
  {
    author: "Louis-Ferdinand C\u00e9line",
    country: "France",
    imageLink: "images/books/voyage-au-bout-de-la-nuit.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Journey_to_the_End_of_the_Night\n",
    pages: 505,
    title: "Journey to the End of the Night",
    year: 1932,
    price: 93,
  },
  {
    author: "Miguel de Cervantes",
    country: "Spain",
    imageLink: "images/books/don-quijote-de-la-mancha.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Don_Quixote\n",
    pages: 1056,
    title: "Don Quijote De La Mancha",
    year: 1610,
    price: 199,
  },
  {
    author: "Geoffrey Chaucer",
    country: "England",
    imageLink: "images/books/the-canterbury-tales.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Canterbury_Tales\n",
    pages: 544,
    title: "The Canterbury Tales",
    year: 1450,
    price: 120,
  },
  {
    author: "Anton Chekhov",
    country: "Russia",
    imageLink: "images/books/stories-of-anton-chekhov.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/List_of_short_stories_by_Anton_Chekhov\n",
    pages: 194,
    title: "Stories",
    year: 1886,
    price: 90,
  },
  {
    author: "Joseph Conrad",
    country: "United Kingdom",
    imageLink: "images/books/nostromo.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Nostromo\n",
    pages: 320,
    title: "Nostromo",
    year: 1904,
    price: 33,
  },
  {
    author: "Charles Dickens",
    country: "United Kingdom",
    imageLink: "images/books/great-expectations.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Great_Expectations\n",
    pages: 194,
    title: "Great Expectations",
    year: 1861,
    price: 44,
  },
  {
    author: "Denis Diderot",
    country: "France",
    imageLink: "images/books/jacques-the-fatalist.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Jacques_the_Fatalist\n",
    pages: 596,
    title: "Jacques the Fatalist",
    year: 1796,
    price: 55,
  },
  {
    author: "Alfred D\u00f6blin",
    country: "Germany",
    imageLink: "images/books/berlin-alexanderplatz.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Berlin_Alexanderplatz\n",
    pages: 600,
    title: "Berlin Alexanderplatz",
    year: 1929,
    price: 66,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/books/crime-and-punishment.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Crime_and_Punishment\n",
    pages: 551,
    title: "Crime and Punishment",
    year: 1866,
    price: 77,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/books/the-idiot.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/The_Idiot\n",
    pages: 656,
    title: "The Idiot",
    year: 1869,
    price: 87,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/books/the-possessed.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Demons_(Dostoyevsky_novel)\n",
    pages: 768,
    title: "The Possessed",
    year: 1872,
    price: 54,
  },
  {
    author: "Fyodor Dostoevsky",
    country: "Russia",
    imageLink: "images/books/the-brothers-karamazov.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/The_Brothers_Karamazov\n",
    pages: 824,
    title: "The Brothers Karamazov",
    year: 1880,
    price: 120,
  },
  {
    author: "George Eliot",
    country: "United Kingdom",
    imageLink: "images/books/middlemarch.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Middlemarch\n",
    pages: 800,
    title: "Middlemarch",
    year: 1871,
    price: 34,
  },
  {
    author: "Ralph Ellison",
    country: "United States",
    imageLink: "images/books/invisible-man.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Invisible_Man\n",
    pages: 581,
    title: "Invisible Man",
    year: 1952,
    price: 76,
  },
  {
    author: "Euripides",
    country: "Greece",
    imageLink: "images/books/medea.jpg",
    language: "Greek",
    link: "https://en.wikipedia.org/wiki/Medea_(play)\n",
    pages: 104,
    title: "Medea",
    year: -431,
    price: 23.15,
  },
  {
    author: "William Faulkner",
    country: "United States",
    imageLink: "images/books/absalom-absalom.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Absalom,_Absalom!\n",
    pages: 313,
    title: "Absalom, Absalom!",
    year: 1936,
    price: 120,
  },
  {
    author: "William Faulkner",
    country: "United States",
    imageLink: "images/books/the-sound-and-the-fury.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Sound_and_the_Fury\n",
    pages: 326,
    title: "The Sound and the Fury",
    year: 1929,
    price: 21,
  },
  {
    author: "Gustave Flaubert",
    country: "France",
    imageLink: "images/books/madame-bovary.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Madame_Bovary\n",
    pages: 528,
    title: "Madame Bovary",
    year: 1857,
    price: 12.99,
  },
  {
    author: "Gustave Flaubert",
    country: "France",
    imageLink: "images/books/l-education-sentimentale.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Sentimental_Education\n",
    pages: 606,
    title: "Sentimental Education",
    year: 1869,
    price: 90,
  },
  {
    author: "Federico Garc\u00eda Lorca",
    country: "Spain",
    imageLink: "images/books/gypsy-ballads.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Gypsy_Ballads\n",
    pages: 218,
    title: "Gypsy Ballads",
    year: 1928,
    price: 91,
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    country: "Colombia",
    imageLink: "images/books/one-hundred-years-of-solitude.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/One_Hundred_Years_of_Solitude\n",
    pages: 417,
    title: "One Hundred Years of Solitude",
    year: 1967,
    price: 92,
  },
  {
    author: "Gabriel Garc\u00eda M\u00e1rquez",
    country: "Colombia",
    imageLink: "images/books/love-in-the-time-of-cholera.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Love_in_the_Time_of_Cholera\n",
    pages: 368,
    title: "Love in the Time of Cholera",
    year: 1985,
    price: 91,
  },
  {
    author: "Johann Wolfgang von Goethe",
    country: "Saxe-Weimar",
    imageLink: "images/books/faust.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Goethe%27s_Faust\n",
    pages: 158,
    title: "Faust",
    year: 1832,
    price: 34,
  },
  {
    author: "Nikolai Gogol",
    country: "Russia",
    imageLink: "images/books/dead-souls.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Dead_Souls\n",
    pages: 432,
    title: "Dead Souls",
    year: 1842,
    price: 45,
  },
  {
    author: "G\u00fcnter Grass",
    country: "Germany",
    imageLink: "images/books/the-tin-drum.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/The_Tin_Drum\n",
    pages: 600,
    title: "The Tin Drum",
    year: 1959,
    price: 54,
  },
  {
    author: "Jo\u00e3o Guimar\u00e3es Rosa",
    country: "Brazil",
    imageLink: "images/books/the-devil-to-pay-in-the-backlands.jpg",
    language: "Portuguese",
    link: "https://en.wikipedia.org/wiki/The_Devil_to_Pay_in_the_Backlands\n",
    pages: 494,
    title: "The Devil to Pay in the Backlands",
    year: 1956,
    price: 99,
  },
  {
    author: "Knut Hamsun",
    country: "Norway",
    imageLink: "images/books/hunger.jpg",
    language: "Norwegian",
    link: "https://en.wikipedia.org/wiki/Hunger_(Hamsun_novel)\n",
    pages: 176,
    title: "Hunger",
    year: 1890,
    price: 120,
  },
  {
    author: "Ernest Hemingway",
    country: "United States",
    imageLink: "images/books/the-old-man-and-the-sea.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea\n",
    pages: 128,
    title: "The Old Man and the Sea",
    year: 1952,
    price: 91,
  },
  {
    author: "Homer",
    country: "Greece",
    imageLink: "images/books/the-iliad-of-homer.jpg",
    language: "Greek",
    link: "https://en.wikipedia.org/wiki/Iliad\n",
    pages: 608,
    title: "Iliad",
    year: -735,
    price: 21,
  },
  {
    author: "Homer",
    country: "Greece",
    imageLink: "images/books/the-odyssey-of-homer.jpg",
    language: "Greek",
    link: "https://en.wikipedia.org/wiki/Odyssey\n",
    pages: 374,
    title: "Odyssey",
    year: -800,
    price: 45,
  },
  {
    author: "Henrik Ibsen",
    country: "Norway",
    imageLink: "images/books/a-Dolls-house.jpg",
    language: "Norwegian",
    link: "https://en.wikipedia.org/wiki/A_Doll%27s_House\n",
    pages: 68,
    title: "A Doll's House",
    year: 1879,
    price: 91,
  },
  {
    author: "James Joyce",
    country: "Irish Free State",
    imageLink: "images/books/ulysses.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Ulysses_(novel)\n",
    pages: 228,
    title: "Ulysses",
    year: 1922,
    price: 45,
  },
  {
    author: "Franz Kafka",
    country: "Czechoslovakia",
    imageLink: "images/books/stories-of-franz-kafka.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Franz_Kafka_bibliography#Short_stories\n",
    pages: 488,
    title: "Stories",
    year: 1924,
    price: 65,
  },
  {
    author: "Franz Kafka",
    country: "Czechoslovakia",
    imageLink: "images/books/the-trial.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/The_Trial\n",
    pages: 160,
    title: "The Trial",
    year: 1925,
    price: 120,
  },
  {
    author: "Franz Kafka",
    country: "Czechoslovakia",
    imageLink: "images/books/the-castle.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/The_Castle_(novel)\n",
    pages: 352,
    title: "The Castle",
    year: 1926,
    price: 120,
  },
  {
    author: "K\u0101lid\u0101sa",
    country: "India",
    imageLink: "images/books/the-recognition-of-shakuntala.jpg",
    language: "Sanskrit",
    link: "https://en.wikipedia.org/wiki/Abhij%C3%B1%C4%81na%C5%9B%C4%81kuntalam\n",
    pages: 147,
    title: "The recognition of Shakuntala",
    year: 150,
    price: 120,
  },
  {
    author: "Yasunari Kawabata",
    country: "Japan",
    imageLink: "images/books/the-sound-of-the-mountain.jpg",
    language: "Japanese",
    link: "https://en.wikipedia.org/wiki/The_Sound_of_the_Mountain\n",
    pages: 288,
    title: "The Sound of the Mountain",
    year: 1954,
    price: 120,
  },
  {
    author: "Nikos Kazantzakis",
    country: "Greece",
    imageLink: "images/books/zorba-the-greek.jpg",
    language: "Greek",
    link: "https://en.wikipedia.org/wiki/Zorba_the_Greek\n",
    pages: 368,
    title: "Zorba the Greek",
    year: 1946,
    price: 120,
  },
  {
    author: "D. H. Lawrence",
    country: "United Kingdom",
    imageLink: "images/books/sons-and-lovers.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Sons_and_Lovers\n",
    pages: 432,
    title: "Sons and Lovers",
    year: 1913,
    price: 120,
  },
  {
    author: "Halld\u00f3r Laxness",
    country: "Iceland",
    imageLink: "images/books/independent-people.jpg",
    language: "Icelandic",
    link: "https://en.wikipedia.org/wiki/Independent_People\n",
    pages: 470,
    title: "Independent People",
    year: 1934,
    price: 120,
  },
  {
    author: "Giacomo Leopardi",
    country: "Italy",
    imageLink: "images/books/poems-giacomo-leopardi.jpg",
    language: "Italian",
    link: "\n",
    pages: 184,
    title: "Poems",
    year: 1818,
    price: 120,
  },
  {
    author: "Doris Lessing",
    country: "United Kingdom",
    imageLink: "images/books/the-golden-notebook.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Golden_Notebook\n",
    pages: 688,
    title: "The Golden Notebook",
    year: 1962,
    price: 120,
  },
  {
    author: "Astrid Lindgren",
    country: "Sweden",
    imageLink: "images/books/pippi-longstocking.jpg",
    language: "Swedish",
    link: "https://en.wikipedia.org/wiki/Pippi_Longstocking\n",
    pages: 160,
    title: "Pippi Longstocking",
    year: 1945,
    price: 120,
  },
  {
    author: "Lu Xun",
    country: "China",
    imageLink: "images/books/diary-of-a-madman.jpg",
    language: "Chinese",
    link: "https://en.wikipedia.org/wiki/A_Madman%27s_Diary\n",
    pages: 389,
    title: "Diary of a Madman",
    year: 1918,
    price: 120,
  },
  {
    author: "Naguib Mahfouz",
    country: "Egypt",
    imageLink: "images/books/children-of-gebelawi.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/Children_of_Gebelawi\n",
    pages: 355,
    title: "Children of Gebelawi",
    year: 1959,
    price: 120,
  },
  {
    author: "Thomas Mann",
    country: "Germany",
    imageLink: "images/books/buddenbrooks.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/Buddenbrooks\n",
    pages: 736,
    title: "Buddenbrooks",
    year: 1901,
    price: 120,
  },
  {
    author: "Thomas Mann",
    country: "Germany",
    imageLink: "images/books/the-magic-mountain.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/The_Magic_Mountain\n",
    pages: 720,
    title: "The Magic Mountain",
    year: 1924,
    price: 120,
  },
  {
    author: "Herman Melville",
    country: "United States",
    imageLink: "images/books/moby-dick.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Moby-Dick\n",
    pages: 378,
    title: "Moby Dick",
    year: 1851,
    price: 120,
  },
  {
    author: "Michel de Montaigne",
    country: "France",
    imageLink: "images/books/essais.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Essays_(Montaigne)\n",
    pages: 404,
    title: "Essays",
    year: 1595,
    price: 120,
  },
  {
    author: "Elsa Morante",
    country: "Italy",
    imageLink: "images/books/history.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/History_(novel)\n",
    pages: 600,
    title: "History",
    year: 1974,
    price: 120,
  },
  {
    author: "Toni Morrison",
    country: "United States",
    imageLink: "images/books/beloved.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Beloved_(novel)\n",
    pages: 321,
    title: "Beloved",
    year: 1987,
    price: 120,
  },
  {
    author: "Murasaki Shikibu",
    country: "Japan",
    imageLink: "images/books/the-tale-of-genji.jpg",
    language: "Japanese",
    link: "https://en.wikipedia.org/wiki/The_Tale_of_Genji\n",
    pages: 1360,
    title: "The Tale of Genji",
    year: 1006,
    price: 120,
  },
  {
    author: "Robert Musil",
    country: "Austria",
    imageLink: "images/books/the-man-without-qualities.jpg",
    language: "German",
    link: "https://en.wikipedia.org/wiki/The_Man_Without_Qualities\n",
    pages: 365,
    title: "The Man Without Qualities",
    year: 1931,
    price: 120,
  },
  {
    author: "Vladimir Nabokov",
    country: "Russia/United States",
    imageLink: "images/books/lolita.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Lolita\n",
    pages: 317,
    title: "Lolita",
    year: 1955,
    price: 120,
  },
  {
    author: "George Orwell",
    country: "United Kingdom",
    imageLink: "images/books/nineteen-eighty-four.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Nineteen_Eighty-Four\n",
    pages: 272,
    title: "Nineteen Eighty-Four",
    year: 1949,
    price: 120,
  },
  {
    author: "Ovid",
    country: "Roman Empire",
    imageLink: "images/books/the-metamorphoses-of-ovid.jpg",
    language: "Classical Latin",
    link: "https://en.wikipedia.org/wiki/Metamorphoses\n",
    pages: 576,
    title: "Metamorphoses",
    year: 100,
    price: 120,
  },
  {
    author: "Fernando Pessoa",
    country: "Portugal",
    imageLink: "images/books/the-book-of-disquiet.jpg",
    language: "Portuguese",
    link: "https://en.wikipedia.org/wiki/The_Book_of_Disquiet\n",
    pages: 272,
    title: "The Book of Disquiet",
    year: 1928,
    price: 120,
  },
  {
    author: "Edgar Allan Poe",
    country: "United States",
    imageLink: "images/books/tales-and-poems-of-edgar-allan-poe.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Edgar_Allan_Poe_bibliography#Tales\n",
    pages: 842,
    title: "Tales",
    year: 1950,
    price: 96,
  },
  {
    author: "Marcel Proust",
    country: "France",
    imageLink: "images/books/a-la-recherche-du-temps-perdu.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/In_Search_of_Lost_Time\n",
    pages: 2408,
    title: "In Search of Lost Time",
    year: 1920,
    price: 96,
  },
  {
    author: "Fran\u00e7ois Rabelais",
    country: "France",
    imageLink: "images/books/gargantua-and-pantagruel.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Gargantua_and_Pantagruel\n",
    pages: 623,
    title: "Gargantua and Pantagruel",
    year: 1533,
    price: 96,
  },
  {
    author: "Juan Rulfo",
    country: "Mexico",
    imageLink: "images/books/pedro-paramo.jpg",
    language: "Spanish",
    link: "https://en.wikipedia.org/wiki/Pedro_P%C3%A1ramo\n",
    pages: 124,
    title: "Pedro P\u00e1ramo",
    year: 1955,
    price: 96,
  },
  {
    author: "Rumi",
    country: "Sultanate of Rum",
    imageLink: "images/books/the-masnavi.jpg",
    language: "Persian",
    link: "https://en.wikipedia.org/wiki/Masnavi\n",
    pages: 438,
    title: "The Masnavi",
    year: 1236,
    price: 96,
  },
  {
    author: "Salman Rushdie",
    country: "United Kingdom, India",
    imageLink: "images/books/midnights-children.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Midnight%27s_Children\n",
    pages: 536,
    title: "Midnight's Children",
    year: 1981,
    price: 96,
  },
  {
    author: "Saadi",
    country: "Persia, Persian Empire",
    imageLink: "images/books/bostan.jpg",
    language: "Persian",
    link: "https://en.wikipedia.org/wiki/Bustan_(book)\n",
    pages: 298,
    title: "Bostan",
    year: 1257,
    price: 96,
  },
  {
    author: "Tayeb Salih",
    country: "Sudan",
    imageLink: "images/books/season-of-migration-to-the-north.jpg",
    language: "Arabic",
    link: "https://en.wikipedia.org/wiki/Season_of_Migration_to_the_North\n",
    pages: 139,
    title: "Season of Migration to the North",
    year: 1966,
    price: 96,
  },
  {
    author: "Jos\u00e9 Saramago",
    country: "Portugal",
    imageLink: "images/books/blindness.jpg",
    language: "Portuguese",
    link: "https://en.wikipedia.org/wiki/Blindness_(novel)\n",
    pages: 352,
    title: "Blindness",
    year: 1995,
    price: 96,
  },
  {
    author: "William Shakespeare",
    country: "England",
    imageLink: "images/books/hamlet.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Hamlet\n",
    pages: 432,
    title: "Hamlet",
    year: 1603,
    price: 91,
  },
  {
    author: "William Shakespeare",
    country: "England",
    imageLink: "images/books/king-lear.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/King_Lear\n",
    pages: 384,
    title: "King Lear",
    year: 1608,
    price: 91,
  },
  {
    author: "William Shakespeare",
    country: "England",
    imageLink: "images/books/othello.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Othello\n",
    pages: 314,
    title: "Othello",
    year: 1609,
    price: 91,
  },
  {
    author: "Sophocles",
    country: "Greece",
    imageLink: "images/books/oedipus-the-king.jpg",
    language: "Greek",
    link: "https://en.wikipedia.org/wiki/Oedipus_the_King\n",
    pages: 88,
    title: "Oedipus the King",
    year: -430,
    price: 91,
  },
  {
    author: "Stendhal",
    country: "France",
    imageLink: "images/books/le-rouge-et-le-noir.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/The_Red_and_the_Black\n",
    pages: 576,
    title: "The Red and the Black",
    year: 1830,
    price: 91,
  },
  {
    author: "Laurence Sterne",
    country: "England",
    imageLink: "images/books/the-life-and-opinions-of-tristram-shandy.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/The_Life_and_Opinions_of_Tristram_Shandy,_Gentleman\n",
    pages: 640,
    title: "The Life And Opinions of Tristram Shandy",
    year: 1760,
    price: 91,
  },
  {
    author: "Italo Svevo",
    country: "Italy",
    imageLink: "images/books/confessions-of-zeno.jpg",
    language: "Italian",
    link: "https://en.wikipedia.org/wiki/Zeno%27s_Conscience\n",
    pages: 412,
    title: "Confessions of Zeno",
    year: 1923,
    price: 91,
  },
  {
    author: "Jonathan Swift",
    country: "Ireland",
    imageLink: "images/books/gullivers-travels.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Gulliver%27s_Travels\n",
    pages: 178,
    title: "Gulliver's Travels",
    year: 1726,
    price: 120,
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/books/war-and-peace.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/War_and_Peace\n",
    pages: 1296,
    title: "War and Peace",
    year: 1867,
    price: 120,
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/books/anna-karenina.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/Anna_Karenina\n",
    pages: 864,
    title: "Anna Karenina",
    year: 1877,
    price: 120,
  },
  {
    author: "Leo Tolstoy",
    country: "Russia",
    imageLink: "images/books/the-death-of-ivan-ilyich.jpg",
    language: "Russian",
    link: "https://en.wikipedia.org/wiki/The_Death_of_Ivan_Ilyich\n",
    pages: 92,
    title: "The Death of Ivan Ilyich",
    year: 1886,
    price: 19,
  },
  {
    author: "Mark Twain",
    country: "United States",
    imageLink: "images/books/the-adventures-of-huckleberry-finn.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Adventures_of_Huckleberry_Finn\n",
    pages: 224,
    title: "The Adventures of Huckleberry Finn",
    year: 1884,
    price: 19,
  },
  {
    author: "Valmiki",
    country: "India",
    imageLink: "images/books/ramayana.jpg",
    language: "Sanskrit",
    link: "https://en.wikipedia.org/wiki/Ramayana\n",
    pages: 152,
    title: "Ramayana",
    year: -450,
    price: 20,
  },
  {
    author: "Virgil",
    country: "Roman Empire",
    imageLink: "images/books/the-aeneid.jpg",
    language: "Classical Latin",
    link: "https://en.wikipedia.org/wiki/Aeneid\n",
    pages: 442,
    title: "The Aeneid",
    year: -23,
    price: 19,
  },
  {
    author: "Vyasa",
    country: "India",
    imageLink: "images/books/the-mahab-harata.jpg",
    language: "Sanskrit",
    link: "https://en.wikipedia.org/wiki/Mahabharata\n",
    pages: 276,
    title: "Mahabharata",
    year: -700,
    price: 19,
  },
  {
    author: "Walt Whitman",
    country: "United States",
    imageLink: "images/books/leaves-of-grass.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Leaves_of_Grass\n",
    pages: 152,
    title: "Leaves of Grass",
    year: 1855,
    price: 19,
  },
  {
    author: "Virginia Woolf",
    country: "United Kingdom",
    imageLink: "images/books/mrs-dalloway.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/Mrs_Dalloway\n",
    pages: 216,
    title: "Mrs Dalloway",
    year: 1925,
    price: 120,
  },
  {
    author: "Virginia Woolf",
    country: "United Kingdom",
    imageLink: "images/books/to-the-lighthouse.jpg",
    language: "English",
    link: "https://en.wikipedia.org/wiki/To_the_Lighthouse\n",
    pages: 209,
    title: "To the Lighthouse",
    year: 1927,
    price: 120,
  },
  {
    author: "Marguerite Yourcenar",
    country: "France/Belgium",
    imageLink: "images/books/memoirs-of-hadrian.jpg",
    language: "French",
    link: "https://en.wikipedia.org/wiki/Memoirs_of_Hadrian\n",
    pages: 408,
    title: "Memoirs of Hadrian",
    year: 1951,
    price: 83,
  },
];
